config/routes.rb
Rails.application.routes.draw do
  root to: 'meters#index' 
  resources :meters do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :equipment
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @meter = Equipment.find(params[:meter_id])
    @comment = @meter.comments.new
  end
  
  def create
    @meter = Equipment.find(params[:meter_id])
    @comment = @meter.comments.new(comment_params)
    if @comment.save
      redirect_to meter_path(params[:meter_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comments).permit(:comment)
  end
  
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  def index
    @meters=Equipment.all
  end

  def show
    @meter = Equipment.find(params[:id])
    @comments = @meter.comments
  end

  def edit
    @meter = Equipment.find(params[:id])
  end
  
  def update
    meter = Equipment.find(params[:id])
    meter_params = params.require(:equipment).permit(:serial, :techid)
    meter.update(meter_params)
    redirect_to meter_path
  end
  
  def new
    @meter = Equipment.new
  end

  def create
    @meter = Equipment.new(equip_params)
    if @meter.save
      redirect_to meter_path(@meter)
    else
      render 'new'
    end
  end

  def destroy
    @meter = Equipment.find(params[:id])
    if @meter.destroy
      flash[:success] = 'Object was successfully deleted.'
      redirect_to meters_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to meter_path(@meter)
    end
  end
  
  
  
  private
  
  def equip_params
    params.require(:equipment).permit(:serial, :techid)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/views/comments/new.html.erb
<p>Enter new comment</p>

<p>Meter Serial: <%= @meter.serial %> </P>

<%= form_with(scope: :comments, url: meter_comments_path(@meter.id)) do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :comment, autofocus: true %>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EquipTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meters/edit.html.erb
<div class="display-3">Edit</div>

<%= form_with(model: @meter, url: meter_path) do |f| %>
  <%= f.label :serial %>
  <%= f.text_field :serial %>
  <%= f.label :techid %>
  <%= f.text_field :techid %>
  <%= f.submit('Submit') %>
<% end %>

app/views/meters/index.html.erb
<div class="display-1">Home</div>

<p class="mt-3">Meter Serial Number</p>

<% @meters.each do |meter| %>
<p class="ms-4">
  <%= link_to(meter.serial, meter_path(meter.id)) %>
</p>  
<% end %>

<%= link_to "New Meter", new_meter_path, class: "mt-4 btn btn-primary"%>

app/views/meters/new.html.erb
<h1 class="h3">New Meter</h1>
<div class="row justify-content-center">
  <%= form_with(model: @meter, scope: :equipment, url: meters_path, class: "col-3") do |f| %>
    <%= f.label :serial, class: "form-label" %>
    <%= f.text_field :serial, class: "mb-4 form-control" %>
    <%= f.label :techid, class: "form-label" %>
    <%= f.text_field :techid, class: "mb-4 form-control" %>
    <%= f.submit %>
  <% end %>
  <!--- <div class="col-3"></div> -->
</div>

app/views/meters/show.html.erb
<div class="row justify-content-center">
  <div class="col-3">
    <div class="h3">Meters Show</div>
    <div class="mt-2">
      <label class="form-label">Meter Serial:</label>
      <label class="form-control"><%= @meter.serial %></label>
    </div>
    <div class="mt-3">  
      <label calls="form-label">Tech Id:</label> 
      <label class="form-control"><%= @meter.techid %></p></label>
    </div class="mb-3">

    <div class="h4 mt-4">Comentarios</div>
    <% @meter.comments.each do |c| %>
      <div class="mb-4">
        <%= c.comment %>
      </div>
    <% end %>
    
    <div class="mt-3">
      <%= link_to "Home", meters_path %>
      <%= link_to "Edit", edit_meter_path(@meter) %>
      <%= link_to "Comments", new_meter_comment_path(@meter.id) %>
      <%= link_to "Delete", meter_path(@meter), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }  %>
    </div>
  </div>
</div>